return {
  global = {
    show_hidden_files = true,
    show_git_ignored_files = true,
    show_git_ignored_parent_files = false,
    python_path = '/usr/bin/python3',
    skip_lsp = false,
    skip_none_ls = false,
  },
  plugins = {
    vim_suda = false,
    rest_nvim = false,
    nvim_dap = false,
    nvim_dap_ui = false,
    nvim_dap_go = false,
    nvim_dap_virtual_text = false,
    mason_nvim_dap_nvim = false,
    nvim_lint = true,
    nvim_lspconfig = true,
    auto_session = false,
    vim_tmux_navigator = false,
    copilot_lua = false,
    codeium_vim = false,
    chatgpt_nvim = false,
    vim_test = false,
    neotest = false,
    neotest_go = false,
    copilot_lualine = false,
  },
}
