return {
  ignore_patters_files = {
    '*.cache',
    '*.swp',
    '*.log',
    '*.phar',
    '*.bak',
    '.git/',
    '.idea/',
    '.code/',
    '.DS_Store',
    '__pycache__',
    'node_modules',
    'vendor',
    'build',
  },

  ignore_patters_tree = {
    '.*.log$',
    '.*.cache$',
    '.*.swp$',
    '.*.log$',
    '.*.phar$',
    '.*.bak$',
    '^.git$',
    '^.idea$',
    '^.code$',
    '.DS_Store',
    '__pycache__$',
    'node_modules$',
    'vendor$',
    'build$',
  },

  vimgrep_arguments = {
    'rg',
    '--color=never',
    '--no-heading',
    '--with-filename',
    '--line-number',
    '--column',
    '--follow',
    '--smart-case',
  },
}
